#!/bin/bash
# 
# Deploy a simple heat stack as a juju charm.
# Joey <joey.mcdonald@nokia.com>

set -x 
debug=''

# This is a problem.. how are we going to make these
# creds portable. They need to exist in the bundle or
# be made available to the build somehow.. hmmmmm..
OS_USERNAME=$(config-get os_username)
OS_TENANT_NAME=$(config-get os_tenant_name)
OS_PASSWORD=$(config-get os_password)
KEYSTONE_ADMIN_TOKEN=$(config-get keystone_admin_token)
OS_AUTH_URL=$(config-get os_auth_url)
NET_ID=$(config-get public_net)

env | grep -q OS_AUTH_URL
if [ $? != 0 ]; then
   echo "Need OpenStack creds to continue." 
   exit 255
fi

function install_heat_client() {

   heat &> /dev/null
   if [ $? != 0 ]; then    
      status-set maintenance "Installing heat client tools."
      apt-get -y install python-heatclient git &> /dev/null
   fi
}

function git_update() {

   if [ -d /var/juju-bootstrap/ ]; then
      status-set maintenance "Updating juju-bootstrap."
      cd /var/juju-bootstrap && git pull &> /dev/null
   else
      status-set maintenance "Installing juju-bootstrap."
      cd /var/ && git clone https://github.com/jmcdice/juju-bootstrap.git
   fi
}

install_heat_client
git_update
