#!/bin/bash
#
# Deploy our stack.
# The install hook will put our git bundle in
# /var/juju-bootstrap/ so we can access stuff we need in there.

OS_USERNAME=$(charm-get os_username)
OS_TENANT_NAME=$(charm-get os_tenant_name) 
OS_PASSWORD=$(charm-get os_password)
KEYSTONE_ADMIN_TOKEN=$(charm-get keystone_admin_token)
OS_AUTH_URL=$(charm-get os_auth_url)
NET_ID=$(charm-get public_net)

heat stack-create -f /var/juju-bootstrap/heat/epdgd_example.yml \
   -P public_net=$NET_ID \
   epdg-stack-00

function stack_deploy() {

   cd /var/juju-bootstrap/heat && bash deploy.sh 
}

echo -n "Starting ePDG services: "
status-set maintenance "Starting ePDG services"
stack_deploy
sleep 3
echo "Ok"


