#!/bin/bash
#
# Deploy our stack.
# The install hook will put our git bundle in
# /var/juju-bootstrap/ so we can access stuff we need in there.

export OS_USERNAME=$(config-get os_username)
export OS_TENANT_NAME=$(config-get os_tenant_name) 
export OS_PASSWORD=$(config-get os_password)
export KEYSTONE_ADMIN_TOKEN=$(config-get keystone_admin_token)
export OS_AUTH_URL=$(config-get os_auth_url)
export NET_ID=$(config-get public_network)

echo -n "Starting ePDG services: "
status-set maintenance "Starting ePDG services"

echo "OS_USERNAME=($OS_USERNAME)"

heat stack-create -f /var/juju-bootstrap/heat/epdgd_example.yml \
   -P public_net=$NET_ID \
   epdg-stack-00


sleep 3
echo "Ok"


